# Generated by Django 2.2.12 on 2021-03-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='contact_number',
        ),
    ]
